// Uncomment for AMD
// define([
// 	'core/DateObject',
// 	'core/Evented',
// 	'core/Map',
// 	'core/Promise',
// 	'core/Registry',
// 	'core/Scheduler',
// 	'core/UrlSearchParams',
// 	'core/WeakMap',
// 	'core/array',
// 	'core/aspect',
// 	'core/decorators',
// 	'core/encoding',
// 	'core/global',
// 	'core/has',
// 	'core/lang',
// 	'core/load',
// 	'core/math',
// 	'core/number',
// 	'core/object',
// 	'core/on',
// 	'core/queue',
// 	'core/request',
// 	'core/string',
// 	'core/text',
// 	'core/util'
// ], (
// 	DateObject,
// 	Evented,
// 	Map,
// 	Promise,
// 	Registry,
// 	Scheduler,
// 	UrlSearchParams,
// 	WeakMap,
// 	array,
// 	aspect,
// 	decorators,
// 	encoding,
// 	global,
// 	has,
// 	lang,
// 	load,
// 	math,
// 	number,
// 	object,
// 	on,
// 	queue,
// 	request,
// 	string,
// 	text,
// 	util
// ) => {
// 	debugger;
// })

// Uncomment for System
Promise.all([
	System.import('core/DateObject'),
	System.import('core/Evented'),
	System.import('core/Map'),
	System.import('core/Promise'),
	System.import('core/Registry'),
	System.import('core/Scheduler'),
	System.import('core/UrlSearchParams'),
	System.import('core/WeakMap'),
	System.import('core/array'),
	System.import('core/aspect'),
	System.import('core/decorators'),
	System.import('core/encoding'),
	System.import('core/global'),
	System.import('core/has'),
	System.import('core/lang'),
	System.import('core/load'),
	System.import('core/math'),
	System.import('core/number'),
	System.import('core/object'),
	System.import('core/on'),
	System.import('core/queue'),
	System.import('core/request'),
	System.import('core/string'),
	System.import('core/text'),
	System.import('core/util')
]).then(([
	DateObject,
	Evented,
	Map,
	Promise,
	Registry,
	Scheduler,
	UrlSearchParams,
	WeakMap,
	array,
	aspect,
	decorators,
	encoding,
	global,
	has,
	lang,
	load,
	math,
	number,
	object,
	on,
	queue,
	request,
	string,
	text,
	util
]) => {
	debugger;
})
